Repository INSRapperswil/nuts, pull requests merged in 2021-11, with the labels that each got.

#42 add Lukas Murer to project maintainers
  pyproject.toml
Labels: documentation

#52 16 more integration self tests for failing results
  nuts/context.py
  nuts/yamlloader.py
  tests/test_class_loading.py
  tests/test_context.py
Labels: enhancement

#49 15 add count self tests
  tests/base_tests/test_napalm_bgp_neighbors.py
  tests/base_tests/test_napalm_interfaces.py
  tests/base_tests/test_napalm_lldp_neighbors.py
  tests/base_tests/test_netmiko_cdp_neighbors.py
  tests/base_tests/test_netmiko_ospf_neighbors.py
Labels: refactor

#53 51 move xxx nornir nuts context.nornir filter up to base class
  nuts/base_tests/napalm_bgp_neighbors.py
  nuts/base_tests/napalm_get_users.py
  nuts/base_tests/napalm_interfaces.py
  nuts/base_tests/napalm_lldp_neighbors.py
  nuts/base_tests/napalm_network_instances.py
  nuts/base_tests/napalm_ping.py
  nuts/base_tests/netmiko_cdp_neighbors.py
  nuts/base_tests/netmiko_iperf.py
  nuts/base_tests/netmiko_ospf_neighbors.py
  nuts/context.py
  tests/test_context.py
Labels: refactor
